    - name: Aceitar todas conexões de entrada
      ansible.builtin.command: iptables -P INPUT ACCEPT

    - name: Aceitar todas conexões de saída
      ansible.builtin.command: iptables -P OUTPUT ACCEPT

    - name: Aceitar todas conexões de encaminhamento
      ansible.builtin.command: iptables -P FORWARD ACCEPT

    - name: Limpar todas as regras do iptables
      ansible.builtin.command: iptables -F

    - name: Salvar regras atuais do iptables
      ansible.builtin.command: iptables-save
      register: iptables_rules

    - name: Salvar regras no arquivo ~/iptables-rules
      copy:
        content: "{{ iptables_rules.stdout }}"
        dest: /home/{{ ansible_user }}/iptables-rules
        owner: "{{ ansible_user }}"
        mode: '0644'

    - name: Executar iptables --flush (novamente, redundante com -F)
      ansible.builtin.command: iptables --flush