    - name: Criar /etc/docker/daemon.json com insecure registry
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "insecure-registries" : ["10.0.15.184:5000"]
          }
        owner: root
        group: root
        mode: '0644'

    - name: Reiniciar serviço do Docker para aplicar a configuração
      service:
        name: docker
        state: restarted