    - name: Instalar repositório Zabbix - Debian/Ubuntu
      ansible.builtin.apt:
        deb: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+ubuntu22.04_all.deb"
        state: present
      tags: install_zabbix_agent
    
    - name: Atualizar cache APT (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      tags: install_zabbix_agent
    
    - name: Instalar Zabbix Agent
      ansible.builtin.package:
        name: zabbix-agent
        state: present
      tags: install_zabbix_agent

    - name: Configurar zabbix_agentd.conf com template
      template:
        src: files/zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
        mode: '0644'
      tags: install_zabbix_agent
        
    - name: Reiniciar Zabbix Agent
      ansible.builtin.service:
        name: zabbix-agent
        state: restarted
      tags: install_zabbix_agent


    

